# Generated by Django 5.0.4 on 2024-05-13 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=150, unique=True)),
                ('description', models.CharField(default=None, max_length=2000)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='service_images/')),
                ('minimum_notice', models.IntegerField(null=True)),
            ],
        ),
    ]
