# Generated by Django 5.0.4 on 2024-05-20 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', 'create__appointment'),
        ('users', '0001_create__custom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=500)),
                ('scheduled_send_datetime', models.DateTimeField()),
                ('actual_sent_datetime', models.DateTimeField(null=True)),
                ('priority', models.CharField(max_length=20)),
                ('channel_specific_info', models.JSONField(null=True)),
                ('response', models.CharField(max_length=500, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='appointments.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='users.customuser')),
            ],
        ),
    ]
