# Generated by Django 5.0.4 on 2024-05-22 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', 'create__appointment'),
        ('notifications', '0001_create__notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='appointments.appointment'),
        ),
    ]
