# Generated by Django 5.0.4 on 2024-05-16 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_create__service'),
        ('users', '0001_create__custom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('confirmation_number', models.IntegerField(null=True, unique=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='users.customuser')),
            ],
        ),
    ]
